accessLog: {}

ping: {}

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

# Somewhat circularly, use the file provider to load details from this configuration file.
providers:
  file:
    filename: /etc/traefik/traefik.yaml

http:
  routers:
    backend:
      rule: "Path(`/graphql`)"
      service: backend
      priority: 20
      entryPoints:
        - "web"
    frontend:
      rule: "PathPrefix(`/`) && !PathRegexp(`^/healthy/?$`)"
      service: frontend
      priority: 10
      entryPoints:
        - "web"
  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend-prod:8000/"
        healthCheck:
          path: /healthy
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend-prod/"
        healthCheck:
          path: /healthy
