"""add_uuid_to_roles_and_permissions

Revision ID: 3c6509c01c97
Revises: d3cab78139a6
Create Date: 2024-08-17 18:24:27.292108

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c6509c01c97"
down_revision: Union[str, None] = "d3cab78139a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions",
        sa.Column("uuid", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    )
    op.add_column(
        "roles",
        sa.Column("uuid", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "uuid")
    op.drop_column("permissions", "uuid")
    # ### end Alembic commands ###
