"""add_additional_indexes

Revision ID: 4948453f7433
Revises: ebb6ad8c9c40
Create Date: 2024-07-19 12:56:34.699519

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4948453f7433"
down_revision: Union[str, None] = "ebb6ad8c9c40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_collections_component", "collections", ["component_id"], unique=False)
    op.create_index("idx_collections_drawer", "collections", ["drawer_id"], unique=False)
    op.create_index("idx_drawers_cabinet", "drawers", ["cabinet_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_drawers_cabinet", table_name="drawers")
    op.drop_index("idx_collections_drawer", table_name="collections")
    op.drop_index("idx_collections_component", table_name="collections")
    # ### end Alembic commands ###
