"""add_search_text_column_to_components

Revision ID: 62a019f1c202
Revises: 132e6f3101a0
Create Date: 2024-08-03 20:02:51.434321

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62a019f1c202"
down_revision: Union[str, None] = "132e6f3101a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "components",
        sa.Column(
            "search_text",
            sa.String(),
            sa.Computed(
                "lower(coalesce(code, '') || coalesce(description, ''))",
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "idx_components_trigrams",
        "components",
        ["search_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_components_trigrams",
        table_name="components",
        postgresql_using="gin",
        postgresql_ops={"search_text": "gin_trgm_ops"},
    )
    op.drop_column("components", "search_text")
    # ### end Alembic commands ###
